version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: 
          name: npm install
          command: npm install
       - run:
          name: Build Vue file
          command: npm run build
       - store_artifacts:
          path: /home/circleci/project/dist
          destination: dist