version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run:
          name: Build Vue file
          command: npm run build
          working_directory: ./articles